name: gpteam
services:
  db:
    image: postgres:latest
    container_name: gpteam-postgres
    profiles:
      - local
      - compose
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:latest
    container_name: gpteam-redis
    profiles:
      - local
      - compose
    ports:
      - "${REDIS_PORT}:6379"

  backend:
    image: mark3317/gpteam-backend:latest
    container_name: gpteam-backend
    profiles:
      - compose
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - FILE_DECODER_URL=${FILE_DECODER_URL}
      - FRONT_URL=${FRONT_URL}
      - AI_URL=${AI_URL}
      - AI_APIKEY=${AI_APIKEY}
    ports:
      - "${BACKEND_PORT}:8080"