name: gpteam-backend
services:
  db:
    image: postgres:latest
    container_name: gpteam-postgres
    profiles:
      - local
      - compose
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  app:
    image: mark3317/gpteam-backend:latest
    container_name: gpteam-backend
    profiles:
      - compose
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - FRONT_URL=${FRONT_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${APP_PORT}:8080"