server:
  servlet:
    context-path: /api
  port: ${BACKEND_PORT:8080}

spring:
  application:
    name: gpteam-backend
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      profiles:
        active: local
  flyway:
    baseline-on-migrate: true

jwt:
  lifetime: 60m
  secret: ${JWT_SECRET}

front:
  url: ${FRONT_URL:*}

ai:
  url: ${AI_URL}
  apikey: ${AI_APIKEY}